apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: api
          image: api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 48090
              name: http

